#!/bin/bash
set -e

# ==============================================================================
# Degradation Combinations Builder
#
# This script builds the 7 input folders representing all combinations of 
# degradations, starting from the doubly clean reference 
# (assets/clean/starless-tiff, generated by build_clean_reference.sh).
# ==============================================================================

CLEAN_TIFF="assets/clean/starless-tiff"
MASK_DIR="assets/outputs-mask"
LIBRARY_DIR="assets/star_library"
ORIG_NPY="assets/outputs-npy"
CORRECTED_NPY="assets/clean/pixelfix-npy"
OUT="assets/combos"
SEED=42

mkdir -p "$OUT"

apply_defects () {
    python apply_defect_delta.py \
        --original-dir "$ORIG_NPY" --corrected-dir "$CORRECTED_NPY" \
        --composite-dir "$1" --out-dir "$2"
}

echo "******** [1/6] inject_stars.py (run once, reused in 4 combos) ********"
python inject_stars.py \
    --starless-dir "$CLEAN_TIFF" \
    --mask-dir "$MASK_DIR" \
    --library-dir "$LIBRARY_DIR" \
    --out-dir "$OUT/_stars_base" \
    --seed "$SEED"

echo "******** [2/6] NPY->TIFF conversion to allow degrading the base with stars ********"
python npy_to_tiff16.py --npy-dir "$OUT/_stars_base" --out-dir "$OUT/_stars_base_tiff"

echo "******** [3/6] degrade_images.py on the clean reference (starless) ********"
python degrade_images.py --tiff-dir "$CLEAN_TIFF" --out-dir "$OUT/_degraded_base"

echo "******** [4/6] degrade_images.py on the base with stars ********"
python degrade_images.py --tiff-dir "$OUT/_stars_base_tiff" --out-dir "$OUT/_degraded_stars_base"

echo "******** [5/6] Assembling the 7 combos ********"

echo "-- SR (stars only) --"
cp -r "$OUT/_stars_base" "$OUT/SR"

echo "-- SU (low resolution only) --"
cp -r "$OUT/_degraded_base/npy" "$OUT/SU"

echo "-- IR (defects only) --"
apply_defects "$CLEAN_TIFF" "$OUT/IR"

echo "-- SR_IR (stars + defects) --"
apply_defects "$OUT/_stars_base" "$OUT/SR_IR"

echo "-- SR_SU (stars + low resolution) --"
cp -r "$OUT/_degraded_stars_base/npy" "$OUT/SR_SU"

echo "-- IR_SU (defects + low resolution) --"
apply_defects "$OUT/_degraded_base/npy" "$OUT/IR_SU"

echo "-- SR_IR_SU (all three) --"
apply_defects "$OUT/_degraded_stars_base/npy" "$OUT/SR_IR_SU"

echo "******** [6/6] Cleaning up intermediate files ********"
rm -rf "$OUT"/_stars_base "$OUT"/_stars_base_tiff "$OUT"/_degraded_base "$OUT"/_degraded_stars_base

echo ""
echo "******** Done. 7 combos ready in $OUT ********"
ls "$OUT"
echo ""
echo "Shared target for make_dataset_merged.py: $CLEAN_TIFF"
echo ""
echo "Next steps:"
echo "  1. python build_crop_manifest.py --clean-dir $CLEAN_TIFF --mask-dir $MASK_DIR"
echo "  2. for each of the 7 folders in $OUT: python make_dataset_merged.py --input-dir $OUT/<COMBO> --target-dir $CLEAN_TIFF --out-dir dataset_merged/<COMBO>"
echo "  3. python check_combo_alignment.py dataset_merged/*"
