#!/bin/bash
# Star Removal (SR) Pipeline Runner
#
# Executes the full sequence of scripts required to build the dataset 
# for Star Removal. It stretches the raw FITS, generates validity masks, 
# runs StarNet2 to create ground-truth starless images and star masks, 
# builds a star library, injects synthetic stars, and finally compiles 
# the training patches.

set -e

# Available flags:
#   --save-png   saves debug PNGs in make_masks and make_dataset

SAVE_PNG=false
for arg in "$@"; do
    case "$arg" in
        --save-png)  SAVE_PNG=true  ;;
    esac
done

echo "******** Starting astro_stretch.py ********"
# --save-tiff is mandatory: it generates the 16-bit TIFFs required by StarNet2 to avoid banding
python astro_stretch.py --save-tiff

echo "******** Starting make_masks.py ********"
if [ "$SAVE_PNG" = true ]; then
    python make_masks.py --save-png
else
    python make_masks.py
fi

echo "******** Starting StarNet2 ********"
mkdir -p assets/outputs-starless
mkdir -p assets/outputs-starmask

# The loop reads the 16-bit TIFFs generated by astro_stretch.py
# The mask is now mandatory to allow build_star_library.py to work
for img in assets/outputs-tiff/*.tif; do
    basename=$(basename "$img" .tif)
    output="assets/outputs-starless/${basename}.tif"
    mask="assets/outputs-starmask/${basename}.tif"
    
    if [ -f "$output" ] && [ -f "$mask" ]; then
        echo "[SKIP] $basename: already processed (starless and mask present)"
        continue
    fi
    
    echo "StarNet2: $basename"
    ./starnet/starnet2 \
        --input "$img" \
        --output "$output" \
        --mask "$mask"
done

echo "******** Starting build_star_library.py ********"
python build_star_library.py

echo "******** Starting inject_stars.py ********"
python inject_stars.py

echo "******** Starting make_dataset_sr.py ********"
if [ "$SAVE_PNG" = true ]; then
    python make_dataset_sr.py --crops-per-image 200 --save-png
else
    python make_dataset_sr.py --crops-per-image 200
fi

echo "******** SR Pipeline completed ********"
